#!/usr/bin/env node
/**
 * Builds the library stylesheet from its area files.
 *
 * The source of the stylesheet is `projects/angular-dockable-desktop/src/styles/parts/NN-area.css`;
 * this script concatenates those files, byte for byte, in file-name order into `styles.css` next to
 * them, which is committed (the gates, the tests and ng-packagr read it by path) and published as
 * `angular-dockable-desktop/styles.css`. Order is the cascade: a later file
 * wins ties with an earlier one, so a file's number says where its rules sit, and a rule moves to
 * another file only together with that consequence in mind.
 *
 *   node scripts/build-css.mjs           write styles.css
 *   node scripts/build-css.mjs --check   exit 1 if styles.css is not what the area files give
 *   node scripts/build-css.mjs --watch   rewrite it whenever an area file changes
 */
import { readFileSync, writeFileSync, readdirSync, watch } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PARTS = join(ROOT, 'projects', 'angular-dockable-desktop', 'src', 'styles', 'parts');
const OUT = join(ROOT, 'projects', 'angular-dockable-desktop', 'src', 'styles', 'styles.css');

export const HEADER = '/* Generated by scripts/build-css.mjs from styles/parts/*.css — edit those files, not this one. */\n';

/** The area files, in the order they are concatenated. */
export const areaFiles = () => readdirSync(PARTS).filter(f => f.endsWith('.css')).sort();

/** The stylesheet the area files give. */
export const buildCss = () => HEADER + areaFiles().map(f => readFileSync(join(PARTS, f), 'utf8')).join('');

const write = () => { writeFileSync(OUT, buildCss()); console.log(`styles.css written from ${areaFiles().length} area files`); };

if (import.meta.url === `file://${process.argv[1]}`) {
  const arg = process.argv[2];
  if (arg === '--check') {
    if (readFileSync(OUT, 'utf8') !== buildCss()) {
      console.error('styles.css is out of date: edit styles/parts/*.css, then run `npm run css`.');
      process.exit(1);
    }
    console.log('styles.css is up to date');
  } else if (arg === '--watch') {
    write();
    watch(PARTS, () => { try { write(); } catch (e) { console.error(e.message); } });
  } else {
    write();
  }
}
